version: '3'

services:

    nginx:
        build:
            context: ../..
            dockerfile: docker/images/nginx/Dockerfile
        container_name: api-nginx
        links:
            - php:php-fpm
